version: '3.8'

services:
  sm-downscaling:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    image: sm-downscaling:latest
    container_name: sm-downscaling
    environment:
      - DATA_DIR_PATH=/DATA
      - PYTHONPATH=/App/src
    volumes:
      - ./src:/App/src
      - ./CHECKPOINTS:/App/CHECKPOINTS
      - /Volumes/Elements SE/Data/SMDownscaling:/DATA
    command: python src/server.py
